In [4]:
import pandas as pd

In [5]:
mdf=pd.read_csv(r"/Users/kishorekumar/Desktop/skillgap analysis/data/raw/ml_jobs.csv")
mdf.sample()

,job_id,job_title,company_name,description,location,experience_level,skills_desc,role_category,url
572,3901175507,IT Product Support Analyst/Data Analyst,Hirexa Solutions,ResponsibilitiesWhat You Will DoRespond prompt...,"Wichita, KS",NaN,NaN,data_analyst,https://www.linkedin.com/jobs/view/3901175507/...

In [6]:
df = pd.read_csv("/Users/kishorekumar/Desktop/skillgap analysis/data/raw/postings.csv")
print(df.shape)
print(df.columns.tolist())
print(df["title"].value_counts().head(20))

(123849, 31)
['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']
title
Sales Manager                      673
Customer Service Representative    373
Project Manager                    354
Administrative Assistant           254
Senior Accountant                  238
Executive Assistant                228
Salesperson                        211
Registered Nurse                   210
Receptionist                       204
Staff Accountant                   200
Account Executive                  195
Retail Sales Associate             190
Sales Associate                    189
Software Engineer                  181
Controller                         175
Account Manager                    171
Store Manager                      166
Senior Software Engineer           162
ASSISTANT STORE MANAGER            161
Assistant Manager                  161
Name: count, dtype: int64

In [7]:
print(df["title"].value_counts())

title
Sales Manager                                       673
Customer Service Representative                     373
Project Manager                                     354
Administrative Assistant                            254
Senior Accountant                                   238
                                                   ...
Cath Lab / IR Technologist (Cert) - Cardiac Cath      1
Energy Administrative Assistant Part Time             1
ASSOCIATE CLIENT SUCCESS MANAGER                      1
Student Nurse - Telemetry                             1
Marketing Social Media Specialist                     1
Name: count, Length: 72521, dtype: int64

In [8]:
mdf=pd.read_csv(r"/Users/kishorekumar/Desktop/skillgap analysis/data/raw/ml_jobs.csv")

In [9]:
mdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1570 entries, 0 to 1569
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            1570 non-null   int64
 1   job_title         1570 non-null   object
 2   company_name      1553 non-null   object
 3   description       1570 non-null   object
 4   location          1570 non-null   object
 5   experience_level  1104 non-null   object
 6   skills_desc       13 non-null     object
 7   role_category     1570 non-null   object
 8   url               1570 non-null   object
dtypes: int64(1), object(8)
memory usage: 110.5+ KB

In [10]:
mdf.skills_desc

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1565    NaN
1566    NaN
1567    NaN
1568    NaN
1569    NaN
Name: skills_desc, Length: 1570, dtype: object

In [11]:
mdf.dtypes

job_id               int64
job_title           object
company_name        object
description         object
location            object
experience_level    object
skills_desc         object
role_category       object
url                 object
dtype: object

In [12]:
mdf[mdf['experience_level'].isna() | (mdf['experience_level'] == '')]

,job_id,job_title,company_name,description,location,experience_level,skills_desc,role_category,url
0,3742692445,Sr Data Engineer with Kafka,ZenithMinds Inc,Data Engineer with Kafka (W2 Only)💯% Remote\nM...,"Austin, TX",NaN,NaN,data_engineer,https://www.linkedin.com/jobs/view/3742692445/...
2,3800272386,Data Science Software Engineer,Sovrinti,Company Overview Sovrinti is a full-service en...,United States,NaN,NaN,data_scientist,https://www.linkedin.com/jobs/view/3800272386/...
3,3800989742,Data Engineer/ETL,SilverSpace Technologies Inc,"Responsibilities:Develop new features, fix bug...","Hartford, CT",NaN,NaN,data_engineer,https://www.linkedin.com/jobs/view/3800989742/...
4,3813645405,Data Analyst,Tenazx Inc,Job Title: Data AnalystDuration: ContractLocat...,"Queens, NY",NaN,NaN,data_analyst,https://www.linkedin.com/jobs/view/3813645405/...
5,3841003722,Senior Data Engineer/Analyst - Full Time,NaN,"Job Type: Full-Time, Permanent \nResponsibilit...","California, United States",NaN,NaN,data_engineer,https://www.linkedin.com/jobs/view/3841003722/...
...,...,...,...,...,...,...,...,...,...
1547,3906240634,Business Intelligence Analyst,Reliance Matrix,Job Responsibilities And Requirements\n\nThe B...,"Philadelphia, PA",NaN,NaN,data_analyst,https://www.linkedin.com/jobs/view/3906240634/...
1548,3906240774,"Senior Software Engineer, Machine Learning",Arcus,"DescriptionAt Arcus, our mission is to advance...","New York, NY",NaN,NaN,ml_engineer,https://www.linkedin.com/jobs/view/3906240774/...
1555,3906251726,Data Analyst II - Staff Credentialing,CHRISTUS Health,Description\n\nSummary:\n\nThis position is re...,"Irving, TX",NaN,NaN,data_analyst,https://www.linkedin.com/jobs/view/3906251726/...
1558,3906252346,Data Scientist,Gensler,"At Gensler, we design for people. We leverage ...","Washington, DC",NaN,NaN,data_scientist,https://www.linkedin.com/jobs/view/3906252346/...
1562,3906255213,Data Scientist,International Paper,Position Title\n\nData Scientist II\n\nPay Rat...,"Memphis, TN",NaN,NaN,data_scientist,https://www.linkedin.com/jobs/view/3906255213/...

In [13]:
mdf.drop('skills_desc', axis=1, inplace=True)

In [14]:
import spacy
nlp = spacy.load("en_core_web_sm")
print("spaCy ready:", nlp.meta["name"])

spaCy ready: core_web_sm

In [15]:
features_df = pd.read_csv( "/Users/kishorekumar/Desktop/skillgap analysis/data/processed/ml_job_features.csv")

In [19]:
features_df.columns

Index(['job_id', 'job_title', 'company_name', 'role_category',
       'experience_level', 'python', 'sql', 'r', 'scala', 'java', 'javascript',
       'scikit_learn', 'pytorch', 'tensorflow', 'keras', 'xgboost', 'lightgbm',
       'catboost', 'huggingface', 'machine_learning', 'deep_learning', 'nlp',
       'computer_vision', 'llm', 'rag', 'feature_engineering',
       'model_deployment', 'classification', 'regression', 'clustering',
       'time_series', 'recommendation', 'reinforcement_learning',
       'generative_ai', 'spark', 'kafka', 'airflow', 'dbt', 'etl',
       'data_pipeline', 'data_warehouse', 'data_lake', 'postgresql', 'mysql',
       'mongodb', 'redis', 'snowflake', 'bigquery', 'redshift',
       'elasticsearch', 'pinecone', 'aws', 'gcp', 'azure', 'docker',
       'kubernetes', 'mlflow', 'kubeflow', 'git', 'cicd', 'tableau',
       'power_bi', 'matplotlib', 'seaborn', 'plotly', 'statistics',
       'probability', 'linear_algebra', 'hypothesis_testing', 'bayesian',
       'agile', 'communication', 'stakeholder'],
      dtype='object')